NEI <- readRDS("summarySCC_PM25.rds")
SCC <- readRDS("Source_Classification_Code.rds")
Index<-grepl("Motor", SCC$Short.Name)
data<-SCC[Index, ]
mdata<-merge(NEI, data, by="SCC")
NEIsub1<-subset(mdata, fips == "24510")
NEIsub2<-subset(mdata, fips == "06037")
year<-c(1999, 2002, 2005, 2008)
png("Plot6.png")
MotorEmissions1<-with(NEIsub1, tapply(Emissions, year, sum, na.rm=T))
MotorEmissions2<-with(NEIsub2, tapply(Emissions, year, sum, na.rm=T))
par(mfrow=c(2, 1))
plot(year, MotorEmissions1, type='l', ylab = "Emissions (Mill. of Tones)")
title(main="Motor vehicle Emissions from 1999 to 2008 in Baltimore City")
plot(year, MotorEmissions2, type='l', ylab = "Emissions (Mill. of Tones)")
title(main="Motor vehicle Emissions from 1999 to 2008 in Los Angeles County")